# Generated by Django 5.1.3 on 2024-11-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateField(auto_now_add=True, help_text='Генерируется автоматически', null=True, verbose_name='Дата присоединения пользователя'),
        ),
    ]
