# Generated by Django 5.1.3 on 2024-11-12 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
    ]
