# Generated by Django 5.1.3 on 2024-11-12 23:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Задача создана', 'Created'), ('Назначен исполнитель', 'Assigned'), ('Задача выполнена', 'Completed'), ('Задача проверена', 'Reviewed')], max_length=20, verbose_name='Тип статуса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания статуса')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Укажите название задачи', max_length=100, verbose_name='Название задачи')),
                ('description', models.TextField(blank=True, help_text='Добавьте текст задачи', null=True, verbose_name='Текст задачи')),
                ('image', models.ImageField(blank=True, help_text='Загрузите изображение для задачи, если это необходимо', null=True, upload_to='tasks/images', verbose_name='Изображение')),
                ('file', models.FileField(blank=True, help_text='Загрузите файл для задачи, если это необходимо', null=True, upload_to='tasks/files', verbose_name='Файл')),
                ('presumable_completion_time', models.DurationField(blank=True, default=datetime.timedelta(seconds=18000), help_text='Укажите предполагаемое время выполнения задачи', null=True, verbose_name='Предполагаемое время выполнения')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
