# Generated by Django 5.1.3 on 2024-11-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='views_amount',
            field=models.PositiveIntegerField(default=0, help_text='Счетчик просмотров задачи', verbose_name='Просмотры'),
        ),
    ]
