# Generated by Django 5.1.3 on 2024-11-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_views_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Укажите, будет ли задача публичной', verbose_name='Флаг публичной/приватной задачи'),
        ),
    ]
