# Generated by Django 5.1.3 on 2024-11-12 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='presumable_completion_time',
            field=models.DurationField(blank=True, default=datetime.timedelta(seconds=18000), help_text='Укажите предполагаемое время выполнения задачи', null=True, verbose_name='Предполагаемое время выполнения'),
        ),
    ]
