# Generated by Django 5.1.3 on 2024-11-12 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_presumable_completion_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='views_amount',
        ),
    ]
