# Generated by Django 5.1.3 on 2024-11-12 20:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания статуса'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='status',
            name='type',
            field=models.CharField(choices=[('Задача создана', 'Created'), ('Назначен исполнитель', 'Assigned'), ('Задача выполнена', 'Completed'), ('Задача проверена', 'Reviewed')], max_length=20, verbose_name='Тип статуса'),
        ),
    ]
